### ISSUE TITLE
Exit on first error

### ISSUE THREAD

**Issue by smallhadroncollider** [develop-me/setup#7]
Use `set -e` to exit on first error?

[More Info](https://stackoverflow.com/questions/1378274/in-a-bash-script-how-can-i-exit-the-entire-script-if-a-certain-condition-occurs)

@oliward Thoughts?

**Comment by oliward** [comment]
@smallhadroncollider 

Yes I think that would be a good idea. Perhaps with final step being saving something out to log file, so you or I can verify that a student's machine did actually complete.

Should help us have confidence all is well, as quite often students giving concerning or confusing responses when asked if it all ran okay!

**Comment by smallhadroncollider** [comment]
Good idea. I'll add a `zsh` alias as the last step.

**Comment by smallhadroncollider** [comment]
Done in [2.1.0](https://github.com/develop-me/bootcamp--setup/releases/tag/2.1.0)
